import pandas as pd 
import numpy as np 
import matplotlib as plt #libraries import 

electoral_comm_an = pd.read_csv('C:/folder/file.csv', sep = ';', encoding='utf-8', usecols = ['KomisjaID', 'Siedziba', 'Gmina', 'Wojewodztwo', 'Uprawnieni', 'OkregID', 'WydaneKarty', 'Zaswiadczenie', 'KartyWyjete', 'KartyNiewazne', 'KartyWazne', 'GlosyNiewazne', 'WieleX', 'BrakX', 'GlosyWazne', 'PIS', 'KO', 'TRZECIADROGA', 'NOWALEWICA', 'KONFEDERACJA']) #This section of the code handles data loading and initial data column selection.

electoral_comm_an['Gmina'].fillna('EmptyFiller', inplace = True)
electoral_comm_an['Wojewodztwo'].fillna('zagranica', inplace = True) #Replacing empty fields in the 'Wojewodztwo' column with the value: 'zagranica'. This ensures that foreign electoral commissions can be easily identified when needed.
electoral_comm_an['niewazne_p'] = round(100 * electoral_comm_an['GlosyNiewazne'] / electoral_comm_an['KartyWazne'], 2)
electoral_comm_an['pis_p'] = round(100 * electoral_comm_an['PIS'] / electoral_comm_an['GlosyWazne'], 2)
electoral_comm_an['ko_p'] = round(100 * electoral_comm_an['KO'] / electoral_comm_an['GlosyWazne'], 2)
electoral_comm_an['nl_p'] = round(100 * electoral_comm_an['NOWALEWICA'] / electoral_comm_an['GlosyWazne'], 2)
electoral_comm_an['3d_p'] = round(100 * electoral_comm_an['TRZECIADROGA'] / electoral_comm_an['GlosyWazne'], 2)
electoral_comm_an['konf_p'] = round(100 * electoral_comm_an['KONFEDERACJA'] / electoral_comm_an['GlosyWazne'], 2)
electoral_comm_an['wielex_p'] = round(100 * electoral_comm_an['WieleX'] / electoral_comm_an['GlosyNiewazne'], 2)
electoral_comm_an['zasw_p'] = round(100 * electoral_comm_an['Zaswiadczenie'] / electoral_comm_an['GlosyWazne'], 2) #The lines of code written above introduce several new columns that calculate the percentage shares of specific categories. These columns will be utilized in subsequent analyses.
electoral_comm_an.fillna(0, inplace = True)

#### VOVIDESHIPS AND COMMUNES ANALYSIS ####

voivodeship_data = {'Wojewodztwo' : ['dolnośląskie', 'kujawsko-pomorskie', 'lubelskie', 'lubuskie', 'mazowieckie', 'małopolskie', 'opolskie', 'podkarpackie', 'podlaskie', 'pomorskie', 'warmińsko-mazurskie', 'wielkopolskie', 'zachodniopomorskie', 'łódzkie', 'śląskie', 'świętokrzyskie'],
                    'Population' : [2897700, 2017700, 2038300, 985500, 5512800, 3430400, 948600, 2085900, 1148700, 2358700, 1374700, 3500000, 1650000, 2394900, 4375900, 1187700],
                    'Surface' : [19947, 17971, 25123, 13988, 35559, 15183, 9412, 17846, 20187, 18323, 24173, 29826, 22905, 18219, 12333, 11710]}
voivodeship_df = pd.DataFrame(voivodeship_data) #Creating a DataFrame object based on a dictionary containing information about Polish voivodeships gathered from Wikipedia.

voivodeship_support = electoral_comm_an.groupby('Wojewodztwo')[['Uprawnieni', 'KO', 'PIS', 'GlosyWazne', 'KomisjaID']].agg({'Uprawnieni' : 'sum', 'KO' : 'sum', 'PIS' : 'sum', 'KomisjaID' : 'count', 'GlosyWazne' : 'sum'}) #Grouping the data by voivodeships ('Wojewodztwo'), using the agg function to sum up the number of votes for the two biggest parties and the overall number of votes, while also counting the number of electoral commissions in each voivodeship. Finally, the reset_index() function is used to avoid having the 'Wojewodztwo' column as part of the index.
voivodeship_support['KO_proc'] = round(100 * voivodeship_support['KO'] / voivodeship_support['GlosyWazne'],2)
voivodeship_support['PIS_proc'] = round(100 * voivodeship_support['PIS'] / voivodeship_support['GlosyWazne'],2)
voivodeship_support.drop(columns = ['KO', 'PIS'], inplace = True)
voivodeship_support.rename({'KomisjaID' : "KomisjaCount"}, axis =1,  inplace = True) #The code lines above create two new columns that represent the percentage vote share for each party in each Voivodeship. It then drops columns that are not necessary for further analysis and renames one column to a more descriptive name.
voivodeship_merged = voivodeship_support.merge(right = voivodeship_df, how = 'left', left_on = 'Wojewodztwo', right_on = 'Wojewodztwo') #Merging the previously created data frame object containing information about voivodeships with the data frame object that includes population and geographic information obtained from Wikipedia. The objects are joined using a 'left' merge as not to lose the information regarding foreign electoral commissions that are not present in the voivodeship_df object.
voivodeship_merged['Upr/Kom'] = round(voivodeship_merged['Uprawnieni'] / voivodeship_merged['KomisjaCount'],2)
voivodeship_merged['Pop/Kom'] = round(voivodeship_merged['Population'] / voivodeship_merged['KomisjaCount'],2)
voivodeship_merged['Pop/Glo'] = round(voivodeship_merged['Population'] / voivodeship_merged['GlosyWazne'],2)
voivodeship_merged['Surf/Kom'] = round(voivodeship_merged['Surface'] / voivodeship_merged['KomisjaCount'],2)
voivodeship_merged['Surf/Glo'] = round(100 * voivodeship_merged['Surface'] / voivodeship_merged['GlosyWazne'],2) #Creating columns that calculate various metrics for further analysis between different voivodeships.
voivodeship_merged.sort_values(by='Upr/Kom', inplace = True)

commune = electoral_comm_an.groupby(['Wojewodztwo','Gmina'])[['Uprawnieni', 'KO', 'PIS', 'GlosyWazne', 'KomisjaID']].agg({'Uprawnieni' : 'sum', 'KO' : 'sum', 'PIS' : 'sum', 'KomisjaID' : 'count', 'GlosyWazne' : 'sum'}).reset_index()
commune['KO_proc'] = round(100 * commune ['KO'] / commune['GlosyWazne'],2)
commune['PIS_proc'] = round(100 * commune['PIS'] / commune['GlosyWazne'],2)
commune.rename({'KomisjaID' : "KomisjaCount"}, axis =1,  inplace = True)
commune['Upr/Kom'] = commune['Uprawnieni'] / commune['KomisjaCount'] #A similar grouping procedure that was executed at the voivodeship level is now being implemented at the commune level. This process includes grouping, summing votes, counting electoral commissions, and generating new columns to compute additional metrics for subsequent analysis.
commune[commune['Wojewodztwo'] == 'opolskie'].sort_values(by='KomisjaCount', ascending = False)

#voivodeship_merged[['Pop/Kom', 'PIS_proc', 'Wojewodztwo']].plot(kind = 'scatter', x = 'Pop/Kom', y = 'PIS_proc', figsize = (15,5))

#*'Upr/Kom' is a metric that calculates the ratio of the number of people assigned to the electoral commissions at the analyzed geographical level (voivodeship or commune) to the total number of electoral commissions that operated in that region during the last election. A lower value indicates that there are fewer people assigned to each electoral commission, resulting in greater voter comfort in that area. However, it's important to note that analyzing solely based on this metric is not the correct approach. If the author were to provide recommendations, a more comprehensive geographical analysis would be necessary.
#1 Among the 7 voivodeships with the lowest 'Upr/Kom' index, there are 3 voivodeships where the percentage vote share between the two biggest parties is nearly the same. In contrast, there are 4 voivodeships where PiS dominated significantly. It's worth noting that there are two more voivodeships dominated by PiS supporters that have a less favorable 'Upr/Kom' ratio for voters: Łódzkie and Małopolskie. To gain further insights, a deeper dive into the details is needed.
#2 Opolskie voivodeship has the lowest 'Upr/Kom' index. However, it's crucial to examine this at the level of each commune within the voivodeship. For example, in the city of Opole, the highest number of electoral commissions were opened, with 85 commissions and almost 97,000 eligible voters, resulting in a 'Upr/Kom' ratio of 1138.5. In this area, KO received 45.1% of the votes, while PiS got 21.4%. On the other hand, the third commune with the highest number of electoral commissions in Opolskie was Gmina Namysłów. Here, there were 38 electoral commissions and 19.8k eligible voters. PiS received 36% of the votes, while KO received 28%, and the 'Upr/Kom' ratio was more than 2 times smaller at only 521.5. It's important to emphasize again that to form a comprehensive opinion about this situation, a thorough geographic analysis is required (people who live in the city probably have a lower distance they need to travel to arrive at an electoral commission). Conducting a comprehensive analysis of electoral commissions that were established prior to the 2023 election is strongly recommended, as it holds a high potential for discovering intriguing insights.
commune[commune['Wojewodztwo'] == 'opolskie'].sort_values(by='KomisjaCount', ascending = False)
#3 Excluding foreign electoral commissions, there is a noticeable trend that in communes where the 'Upr/Kom' metric is the lowest, PiS tends to receive 50 - 70% of the votes, with a few exceptions like Gmina Milejczyce and Gmina Hajnówka, both in Voivodeship Podlaskie. In these communes, neither PiS nor KO receives a percentage share of votes much higher than 30%. After a brief inspection, it becomes apparent that the reason for this situation is the significantly higher popularity of Trzecia Droga, primarily linked to the fact that this is the district where the party leader, Szymon Hołownia, was a candidate.
commune[(commune['Wojewodztwo'] != 'zagranica') & (commune['PIS_proc'] < 40) & (commune['Upr/Kom'] < 400)] .sort_values(by = 'Upr/Kom').head(50)
#4a Another hypothesis to verify was whether the 'Upr/Kom' ratio in cities would be the smallest in cities where PiS is the most popular party and the highest in cities where its biggest rival, KO, is more popular. In the 'Gmina' column, communes that start with 'gm.' were filtered out using the startswith function, along with the 'zagranica' group. This approach focused solely on electoral commissions in medium to large Polish cities, excluding smaller cities, villages, and those abroad. Next, a new column, 'who_is_winner,' was created. A specially designed function assigned the value 'ko' if the percentage share of votes gathered by KO was at least 5 percentage points higher than the percentage share of votes gathered by PiS. It assigned 'pis' if PiS was at least 5 percentage points stronger, and 'tie' if the difference in the vote share gathered by these two parties was smaller than 5 percentage points. The count of 'ko,' 'pis,' and 'tie' was calculated for the top 50 cities with the smallest and the highest 'Upr/Kom' ratio.
#4b There were 319 medium to larger Polish cities that were analyzed after applying the filters described above. Analyzing the percentage share of votes for political parties, in 45.1% of the analyzed cities, KO won by more than a 5% margin, while PIS outperformed KO by 5% or more in 32.9% of the cities. In 22.0% of these cities, the difference between these two parties was less than 5 percentage points. In the top 50 communes with the lowest 'Upr/Kom' ratio, PIS had a lead of 5 percentage points or more in 50% of them, while KO won in 26%. In the top 50 communes with the highest 'Upr/Kom' ratio, PIS emerged victorious by 5 percentage points or more in only 12% of them, with KO prevailing in 74%. Based on these observations, one can conclude that the 'Upr/Kom' ratio tends to be lower in cities where PIS enjoys greater popularity and notably higher in cities where their rivals, such as KO, dominate. This raises the question of whether this disparity is a deliberate plan or design, or if it is merely the result of unfortunate errors in the management, which have led to thousands of voters waiting for many hours to participate in the election process. However, determining the answer to this question falls outside the scope of this analysis.
city_filter = commune['Gmina'].str.startswith('gm.')
commune['who_is_winner'] = commune.apply(lambda row: 'ko' if row['KO_proc'] - row['PIS_proc'] >= 5 else ('pis' if row['PIS_proc'] - row['KO_proc'] >= 5 else 'tie'), axis = 1)
top50 = commune[~city_filter & ~(commune['Wojewodztwo'] == 'zagranica')].sort_values(by = 'Upr/Kom').head(50)
worst50 = commune[~city_filter & ~(commune['Wojewodztwo'] == 'zagranica')].sort_values(by = 'Upr/Kom', ascending = False).head(50)
cities = commune[~city_filter & ~(commune['Wojewodztwo'] == 'zagranica')]
cities['who_is_winner'].value_counts() #code was executed also for variables top50 and worst50.

#### ANALYSIS OF ELECTORAL COMMISSIONS GROUPED BY SIZE ####

electoral_comm_an.sort_values(by = 'GlosyWazne', ascending = True, inplace = True)

def size_analyzer(df = electoral_comm_an):  #The function receives a DataFrame object as a parameter and modifies it within its body. First, the function groups the data by its last column, which will be created later and named based on the number of votes received in each of the commissions. The 'agg' function is then applied to sum the values for certain categories and count the number of commissions within each group. Additionally, the function creates new columns that calculate the percentage share of specific categories relative to the total number of votes within each group. Finally, the modified DataFrame is returned by this function, ready for further analysis.
    new_df  = df.groupby(by=list(electoral_comm_an.columns)[-1])[['KomisjaID','GlosyWazne', 'KO', 'PIS', 'GlosyNiewazne', 'WieleX', 'BrakX', 'Zaswiadczenie']].agg({'KomisjaID' : 'count', 'GlosyWazne' : 'sum', 'KO' : 'sum', 'PIS' : 'sum', 'GlosyNiewazne' : 'sum', 'WieleX' : 'sum', 'BrakX' : 'sum', 'Zaswiadczenie' : 'sum'}).reset_index().sort_values(by=list(electoral_comm_an.columns)[-1])
    new_df['Glo/Kom'] = round(new_df['GlosyWazne'] / new_df['KomisjaID'],2)
    new_df.rename({'KomisjaID' : "KomisjaCount"}, axis =1,  inplace = True)
    new_df['Votes_pct'] = round(100 * new_df['GlosyWazne'] / new_df['GlosyWazne'].sum(), 2)
    new_df['KO'] = round(100 * new_df['KO'] / new_df['GlosyWazne'], 2)
    new_df['PIS'] = round(100 * new_df['PIS'] / new_df['GlosyWazne'], 2)
    new_df['WieleX'] = round(100 * new_df['WieleX'] / new_df['GlosyNiewazne'], 2)
    new_df['BrakX'] = round(100 * new_df['BrakX'] / new_df['GlosyNiewazne'], 2)
    new_df['GlosyNiewazne'] = round(100 * new_df['GlosyNiewazne'] / new_df['GlosyWazne'], 2)
    new_df['Zaswiadczenie'] = round(100 * new_df['Zaswiadczenie'] / new_df['GlosyWazne'], 2)
    return new_df

electoral_comm_an['GrupaGlosyWazne'] = electoral_comm_an['GlosyWazne'].apply(lambda x: 'A. [0,25]' if x <= 25 else ('B. (25,50]' if x <= 50 else ('C. (50,100]' if x <= 100 else ('D. (100,150]' if x <= 150 else ('E. (150,200]' if x <= 200 else ('F. (200,250]' if x <= 250 else 'G. >250'))))))
small_com_sizes = size_analyzer(electoral_comm_an)  #Creating a new column in which the value is determined by a function based on the number of people who voted in that electoral commission. The assignment to one of the seven groups is made according to the number of votes cast in each electoral commission.

electoral_comm_an['GrupaGlosyWazne'] = electoral_comm_an['GlosyWazne'].apply(lambda x: 'A. [0,1500]' if x <= 1500 else ('B. (1500,1750]' if x <= 1750 else ('C. (1750,2000]' if x <= 2000 else ('D. (2000,2250]' if x <= 2250 else ('E. (2250,2500]' if x <= 2500 else ('F. (2500,2750]' if x <= 2750 else 'G. >2750'))))))
big_com_sizes = size_analyzer(electoral_comm_an)

electoral_comm_an['GrupaGlosyWazne'] = electoral_comm_an['GlosyWazne'].apply(lambda x: 'A. [0,250]' if x <= 250 else ('B. (250,500]' if x <= 500 else ('C. (500,750]' if x <= 750 else ('D. (750,1000]' if x <= 1000 else ('E. (1000,1250]' if x <= 1250 else ('F. (1250,1500]' if x <= 1500 else 'G. >1500'))))))
all_com_sizes = size_analyzer(electoral_comm_an)
all_com_sizes.insert(2, 'KomisjaCount_pct', round(100 * all_com_sizes['KomisjaCount'] / all_com_sizes['KomisjaCount'].sum(),2))

#1 Electoral commissions where 250 or fewer votes were cast constitute almost 22% of all electoral commissions. However, these commissions accounted for less than 5% of the overall votes. The difference is quite significant. Such commissions are the ones with the highest percentage of votes going to PiS and the highest percentage of invalid votes (the share of invalid votes is 5 times higher than in the largest commissions: 4.21% vs 0.85%). Upon closer examination, it becomes evident that these smaller commissions are primarily located in places providing medical care (e.g., hospitals), facilities for the elderly (e.g., Dom Pomocy Społecznej), locations outside of Poland, such as Dakar, Iraq, Brasilia, and very small villages (mainly electoral commissions where more than 100 votes were cast).
#2 A closer examination of smaller electoral commissions (data frame: small_com_sizes) reveals interesting insights. The smallest electoral commissions have the highest proportion of invalid votes, reaching 20.76%. Additionally, the share of blank voting cards is atypical in these commissions, standing at 62.4% (compared to 30-40% in electoral commissions of different sizes). These electoral commissions are primarily located in hospitals and facilities where elderly people are being cared for (DPS). The author wants to emphasize that he is observing trends and providing insights rather than offering explanations, as he is not a political expert and does not possess sufficient knowledge of the election process to explain these atypical values that characterize electoral commissions of this size.
#3 The more votes were cast in an electoral commission, the lower the percentage of invalid votes recorded. The author is attempting to identify trends and derive insights from the data rather than providing explanations. However, one possible explanation for this trend could be based on the author's personal experience. It's unlikely that voters would wait for more than three hours to cast an invalid vote. Among the top 50 largest electoral commissions, the percentage share of invalid votes varies from 0.0% to 1.2%, with a mean of 0.66% and a similar median of 0.65%. There doesn't seem to be a clear strategy for casting invalid votes in the largest electoral commissions: in 50% of them, there were more cards with more than one 'X' than blank cards. The opposite situation was observed in 44% of the largest electoral commissions, while in 6%, the ratio was equal.
#4 The top 50 largest electoral commissions represent a different universe compared to the smallest electoral commissions. Out of these 50, only three had PiS shares in votes above 20%. One of these electoral commissions was located in Rome (perhaps due to its proximity to the Vatican), and the other two were in Warsaw. In twelve of the largest commissions, PiS support was below 10%, with seven located in Poland and five abroad. Among the largest electoral commissions, nearly half of them were located abroad in European Union countries. Hopefully, in the next election, the newly chosen government will organize more electoral commissions abroad and in the largest cities, reducing the need for people to demonstrate great patience and persistence as they did on October 15, 2023. Only great civic attitude should remain a constant in the future.
#* The author was considering analyzing the phenomenon of 'voting tourism' that occurred during the last election. Unfortunately, it is unclear if the metric described as 'Zaswiadczenie' covers both: people who could choose any electoral commission during the elections because they had a special document to do so, and people who changed their electoral commission to a different one before the elections without having the right to choose an electoral commission on the day of elections. It is probable that the 'Zaswiadczenie' field represents only the first group of voters who did not visit their original electoral commission.

#### ELECTORAL COMMISSIONS OUTLIERS ####

electoral_comm_an.sort_values(by='GlosyWazne', ascending = False, inplace = True)

#1 The code line below applies multiple filters to identify electoral commissions that meet specific criteria. The author aimed to identify electoral commissions where one of the democratic opposition parties received at least 75% of the votes, and at least 5 votes were cast, to exclude cases where only 1 or 2 votes were cast and 100% support for one party was common. Eight such electoral commissions were found in Poland: four were dominated by Koalicja Obywatelska, and four were dominated by Trzecia Droga. No electoral commission dominated by Nowa Lewica was identified. The number of votes cast in these commissions ranged from 17 to 60. In one of these places, the share of invalid votes was high, approximately 25%, and all of these invalid votes were blank. It's worth noting that similar cases of a high percentage of invalid votes in Dom Pomocy Społecznej are not difficult to find.
electoral_comm_an[( (electoral_comm_an['ko_p'] > 75) | (electoral_comm_an['nl_p'] > 75) | (electoral_comm_an['3d_p'] > 75) ) & (electoral_comm_an['GlosyWazne'] >= 5)].head(50)
#2 A similar line of code, with the same set of conditions (at least 75% of the votes for PiS and at least 5 votes cast), is fulfilled by 403 electoral commissions. This is 50 times more than in the case of similar domination by one of the opposition parties. Among these, there were four electoral commissions where more than one thousand votes were cast, and PiS gathered at least 75% of the votes share. To add here, none of these commissions (and this is true for the top 50 with the highest number of votes cast and dominated by PiS) had a very high share of invalid votes. However, there were 10 electoral commissions where PiS received over 75% of the votes, with more than 5 votes cast, and a share of invalid votes exceeding 25% (in some cases, even reaching 46%). In these instances, the proportion of ballots with multiple 'X' marks among the invalid votes varied from 30% to 100%. These conditions were consistently observed in locations associated with Dom Pomocy Społecznej or medical facilities.
electoral_comm_an[(electoral_comm_an['pis_p'] > 75) & (electoral_comm_an['GlosyWazne'] >= 5)].head(50)
#3 Only 12 electoral commissions had no votes for PiS, while 147 electoral commissions received no votes for KO (two commissions were excluded as no one voted there). The commission with the highest number of votes: 22, that had zero votes for PiS and was dominated by Trzecia Droga, which received 86.4% support there. In contrast, there were four electoral commissions where no one voted for KO, and one of them had even 152 votes cast, making it the commission with the highest number of votes where no one chose KO. These electoral commissions, where the second-largest party in Poland received no votes, were fully dominated by PiS, which garnered 60% to 95% of all votes cast in those points.
len(electoral_comm_an[['Siedziba', 'Gmina', 'Wojewodztwo', 'Uprawnieni', 'WydaneKarty', 'GlosyWazne', 'niewazne_p', 'pis_p', 'ko_p', 'nl_p', '3d_p', 'konf_p', 'wielex_p', 'zasw_p']][electoral_comm_an['ko_p'] == 0])
#4 In contrast, Konfederacja received over 30% of all votes in just four electoral commissions. In comparison, Nowa Lewica dominated 12 times more electoral commissions, achieving this goal in 48 commissions, even though their overall vote count was just 1.45% higher than that of Konfederacja.

reduced_electoral_df = electoral_comm_an[['Siedziba', 'Gmina', 'Wojewodztwo', 'Uprawnieni', 'WydaneKarty', 'GlosyWazne', 'niewazne_p', 'pis_p', 'ko_p', 'nl_p', '3d_p', 'konf_p', 'wielex_p', 'zasw_p']]

#1 There were 519 medium and large-sized electoral commissions (with more than 500 votes cast) where PiS received less than 15% of the vote share. These electoral commissions were sorted by PiS's percentage share in votes, starting from the lowest, and the top 50 electoral commissions were examined. The lowest support for PiS was observed abroad, in EU and Asian cities, with the lowest percentage share (2-5%) in such warm and sunny places as Bali, Las Palmas, or Malaga. Within Poland, the lowest percentage of votes for PiS was recorded in Wroclaw - Jagodno (notably known for people waiting until 3 AM to cast their votes) and two primary schools in Poznan. Interestingly, among the top 50 medium and large-sized electoral commissions, four prisons were identified.
reduced_electoral_df[(reduced_electoral_df['pis_p'] <15) & (reduced_electoral_df['GlosyWazne'] > 500)].sort_values(by='pis_p', ascending = True)
#2 There were 2,107 medium and large-sized electoral commissions where Koalicja Obywatelska received less than 15% of the support. The majority of them (1,820) were medium-sized commissions (with 500 - 1,000 votes). Among the larger commissions (>1,000 votes), KO received less than 15% in 287 locations, while PiS had a similarly low score in 433 larger commissions. When examining the top 50 medium and large-sized commissions with the worst percentage share for KO, almost 80% of these were located in three voivodeships: 'podkarpackie,' 'lubelskie,' and 'malopolskie.' The locations that gave KO the worst results were often medium-sized (500 - 800 votes) and were strongly dominated by PiS (vote share of 79 - 81%). The correlation between poor results for KO and excellent results for PiS is evident. Among the top 50 worst medium and large-sized commissions for KO, there were only two cases where PiS received less than 50% of the votes (47-48%), and in these two commissions, Trzecia Droga achieved excellent results (38 - 40%).
#3 The scatter plot charts below depict the support for each political party (Y-axis) against the number of votes cast in the electoral commission (X-axis). Each point on the chart represents one electoral commission. An evident trend is noticeable for the two largest parties: as the size of the electoral commission increases, the percentage votes share for PiS decreases, while the opposite trend is clearly visible for KO.
#4 The scatter plot for Nowa Lewica clearly indicates that this party was more likely to receive a higher score (percentage share in casted votes) when the electoral commission was larger. The minimum possible support levels increased with the number of votes given in the electoral commission, while the maximum support levels remained relatively consistent.
#5 The chart for Konfederacja reveals an interesting pattern. In smaller electoral commissions, there is, of course, more randomness in the percentage support for the party. However, as we start to analyze electoral commissions where approximately 300 or more votes were cast, the minimum support for the party almost never falls below +/- 4 - 4.5 percentage points, except for singular cases. This pattern is different from Nowa Lewica, where in electoral commissions with less than 1,000 votes, it's easier to identify places where the party received only 1-2% support. For Konfederacja, the baseline support level is much higher, and it is highly improbable to receive lower support, around 4% (judging by the visualization).

reduced_electoral_df[['GlosyWazne', 'pis_p']].plot(kind = 'scatter', x = 'GlosyWazne', y = 'pis_p', color = 'Red', alpha = 0.03, s = 18, edgecolor='Black', linewidth=0.1)
reduced_electoral_df[['GlosyWazne', 'ko_p']].plot(kind = 'scatter', x = 'GlosyWazne', y = 'ko_p', color = 'Blue', alpha = 0.03, s = 18, edgecolor='Black', linewidth=0.1)
reduced_electoral_df[['GlosyWazne', '3d_p']].plot(kind = 'scatter', x = 'GlosyWazne', y = '3d_p', color = 'Green', alpha = 0.03, s = 18, edgecolor='Black', linewidth=0.1)
reduced_electoral_df[['GlosyWazne', 'nl_p']].plot(kind = 'scatter', x = 'GlosyWazne', y = 'nl_p', color = 'Violet', alpha = 0.03, s = 18, edgecolor='Black', linewidth=0.1)
reduced_electoral_df[['GlosyWazne', 'konf_p']].plot(kind = 'scatter', x = 'GlosyWazne', y = 'konf_p', color = 'Brown', alpha = 0.03, s = 18, edgecolor='Black', linewidth=0.1)

#1 There were a total of 178 electoral commissions in Poland where the percentage share of invalid votes exceeded 25%. These electoral commissions were sorted by the number of votes cast in each commission, and the top 50 were examined. The highest number of votes cast in an electoral commission with a percentage of invalid votes higher than 25% was 62. Among the 49 out of 50 inspected locations, they were mainly Domy Pomocy Spolecznej (or similar medical institutions). In most of these places, there were more invalid votes due to the lack of 'X' marked on the voting card (ranging from 60% to 90%), leaving only 10-40% for too many 'X' marked on the voting card.
#2 PIS was mainly receiving between 50% and 80% of all votes cast in these commissions. This fact is not surprising, given that the party is very popular among elderly people. What did catch attention, however, were three places where the second-largest party, KO, received zero votes. In locations where approximately 30 votes were cast, and mostly elderly people voted, this may not seem highly improbable. One point of particular interest among those TOP50 inspected was Zaklad Karny w Ilawie, which was the only non-medical institution identified. It had a very high percentage of votes for PIS: 25.5%. This score appears significantly high, considering that PIS tends to receive single-digit support in most prisons.
reduced_electoral_df.sort_values(by='GlosyWazne', ascending = False, inplace = True)
reduced_electoral_df[reduced_electoral_df['niewazne_p'] > 25].head(50)
